version: '2'

services:
  param-search-paper:
    image: phizaz/nofold-ssl
    volumes:
      - ./:/run
    working_dir: /run/src
    environment:
      - PYTHONUNBUFFERED=1
    command: python parameter_search.py search_space_paper.json

  param-search-novel-1-2-3hp:
    image: phizaz/nofold-ssl
    volumes:
      - ./:/run
    working_dir: /run/src
    environment:
      - PYTHONUNBUFFERED=1
    command: python parameter_search.py search_space_novel-1-2-3hp.json